### ISSUE TITLE
Assign an address to each node

### ISSUE THREAD

**Issue by kostjaigin** [cmdruid/regtest-node#21]
Hi!

I wanted to play around with the containers and try out my new plugin on them. For my plugin I need to send messages to connected nodes, just like in the messages plugin that is provided by default in the run folder. I assume some networking setup might cause problems - when Alice sends a msg, it gets queued, but my dear Bob never receives it :( 

```
root@alice:~# lcli sendmessage 0343c4d8f488a4444cb798d7b519acdd9e68ffa1fc416ac6b2506570ab5b3a64df "Hello Bob!"
{
   "status": "Message sent to connectd for delivery"
} 
``` 

As I saw, nodes don't get any address assigned (at least if I go to particular node and call `lcli getinfo` all nodes addresses are empty). Mb it causes trouble for the plugin. Does messages plugin work for you? Mb I am viewing wrong logs (I expect to see it either in container logs or in the stout)

```
root@alice:~# lcli getinfo
{
   "id": "0255aa99cb062f818138d023ea1cd79efc29b26077d9e969e9f80468d5c01639a4",
   "alias": "LOUDWATCH-v0.11.2",
   "color": "0255aa",
   "num_peers": 3,
   "num_pending_channels": 0,
   "num_active_channels": 3,
   "num_inactive_channels": 0,
   "address": [],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 19846
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 19846
      }
   ],
   "version": "v0.11.2",
   "blockheight": 174,
   "network": "regtest",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/data/lightning/regtest",
   "our_features": {
      "init": "80282a69a2",
      "node": "800080282a69a2",
      "channel": "",
      "invoice": "02000020024100"
   }
}
```

**Comment by cmdruid** [comment]
Hello! Hopefully I can help clarify some things.

To my knowledge, the "address" field will only be populated if you configure the lightning node to bind to a specific address. Otherwise, the node will bind to network interfaces instead, and the "binding" field should reflect those interfaces. Internally, your node will be listing on a port, and all external traffic bound for that port will be received by the node.

Have you checked the lightningd logfile? (terminal shortcut 'ldlog') I just checked with a test instance to see if the plugin is working, and I am able to receive a message. Core Lightning plugins are a bit difficult to work with regarding printing output, as they capture the entire stdin/stdout stream for the plugin. You may have to rely on checking the log for stdout output. There may be other workarounds for printing output, but it has to be outside the plugin process for it to work. Let me know if that helps!

**Comment by kostjaigin** [comment]
Hello hello! 

Thank you so much for the hint with the lightningd log file and for the fast response! I indeed discovered the replies in there. It helped big time!
